version: "3.9"

services:
  db:
    image: postgres:15
    container_name: ems_db
    environment:
      POSTGRES_DB: ems
      POSTGRES_USER: ems_user
      POSTGRES_PASSWORD: StrongPass!234
    ports:
      - "5433:5432"   # host:container (5433 on your PC to avoid clashing)
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ems_user -d ems"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build: .
    container_name: ems_web
    depends_on:
      db:
        condition: service_healthy
    environment:
      DEBUG: "True"
      SECRET_KEY: change-me
      ALLOWED_HOSTS: 127.0.0.1,localhost,0.0.0.0
      DB_NAME: ems
      DB_USER: ems_user
      DB_PASSWORD: StrongPass!234
      DB_HOST: db
      DB_PORT: "5432"
    ports:
      - "8000:8000"
    volumes:
      - .:/app

volumes:
  pgdata: